on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: az500crs.azurecr.io
        username: ${{ secrets.acr_az500crs_username }}
        password: ${{ secrets.acr_az500crs_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/1.1" -f  "https://github.com/Azure-Samples/azure-voting-app-redis.git" -t az500crs.azurecr.io/azdemoaks:${{ github.sha }}
        docker push az500crs.azurecr.io/azdemoaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_azdemoaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azdemoaks8b3d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azdemoaks8b3d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azdemoaks8b3d
        container-registry-url: az500crs.azurecr.io
        container-registry-username: ${{ secrets.acr_az500crs_username }}
        container-registry-password: ${{ secrets.acr_az500crs_password }}
        secret-name: azdemoaksdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: azdemoaks8b3d
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          az500crs.azurecr.io/azdemoaks:${{ github.sha }}
        imagepullsecrets: |
          azdemoaksdockerauth